dataset_name: anet-audio
train_split: ['training']
val_split: ['validation']
dataset: {
  json_file: /home/ed/actionformer_release/data/anet/anet1.3_tsp_filtered.json,
  feat_folder: /mnt/welles/scratch/datasets/Activity-Net/v1-3/tsp_feats/tsp_features,
  audio_folder: /mnt/welles/scratch/datasets/Activity-Net/v1-3/vgg_feats,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 512,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  # upsample the features to a fixed length of 192
  max_seq_len: 192,
  force_upsampling: True,
  use_audio: True,
  audio_format: vgg,
  audio_fuse: late,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  # 192 - 96 - 48 - 24 - 12 - 6
  n_mha_win_size: [7, 7, 7, 7, 7, -1],
  # shrink the model for reduced input feature channels
  n_head: 4,
  embd_dim: 256,
  audio_embd_dim: 128,
  fpn_dim: 256,
  head_dim: 256,
  fpn_norm: groupnorm,
  use_abs_pe: True,

  backbone_type: convPooler,
  backbone_arch: [2, 5],
  audio_embd_dim: 128,
  audio_fusion_loc: ["pre-neck", "pre-cls"],  # pre-neck, pre-backbone, pre-cls, pre-reg
  audio_fusion_method: max_pool, # concat, sum, cross_att
}
opt: {
  learning_rate: 0.0001,
  epochs: 10,
  weight_decay: 0.05,
}
loader: {
  batch_size: 16,
}
train_cfg: {
  init_loss_norm: 200,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  droppath: 0.2,
  loss_weight: 2.0,
  use_audio: True
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.9,
  pre_nms_topk: 2000,
  # max of 100 predictions per video
  max_seg_num: 100,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma : 0.75,
  ext_score_file: /home/ed/actionformer_release/data/anet/cuhk_val_simp_share.json,
  duration_thresh: 0.001,
}
output_folder: ./ckpt/
